version: "3.7"

services:
  rstudio-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ../bin:/home/rstudio/bin
      - ../data:/home/rstudio/data
      - ../doc:/home/rstudio/doc
      - ../results:/home/rstudio/results
      - ../src:/home/rstudio/src
    environment:
      - PASSWORD=password
    init: true
    stdin_open: true
    tty: true    
